/**
 * Manifest type definitions
 * Auto-generated by scripts/generate-data-manifests.js
 */

export interface ManifestEntry {
	id: string;
	name: string;
	type: string;
	level: number;
	path: string;
}

export interface DataManifest {
	category: string;
	generated: string;
	count: number;
	entries: ManifestEntry[];
}
